version: '3.4'

services:
  db:
    restart: always
    image: postgres:9.6
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "user"
      POSTGRES_USER: "user"
      POSTGRES_DB: "polldemo"
    command: postgres